name: "Setup Go"
description: |
  Sets up the Go environment for tests, builds, etc.

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod
        cache: false

    - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      id: go-cache
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: go-${{ hashFiles('go.sum') }}
        restore-keys: |
          go-

    - name: go mod download
      shell: bash
      run: go mod download -x

    - uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      if: github.ref_name == 'main'
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ steps.go-cache.outputs.cache-primary-key }}

    - name: Setup vite-plus
      uses: voidzero-dev/setup-vp@49c3e4e92c52e7f8392712a9267bbe71c5ab30e5 # v1.19.0
      with:
        cache: true
        cache-save: ${{ github.ref_name == 'main' }}
        node-version-file: .node-version
