catalogs:
  dev:
    "@arethetypeswrong/core": 0.18.5
    "@rolldown/plugin-babel": 0.2.3
    "@types/node": ^26.1.2
    "@types/react": 19.2.17
    "@types/react-dom": 19.2.3
    "@vitejs/plugin-react": 6.0.3
    "@vitest/browser": 4.1.10
    "@vitest/browser-playwright": 4.1.10
    playwright: 1.61.1
    publint: 0.3.22
    typescript: 7.0.2
    unplugin-unused: 0.5.7
    vitest-browser-react: 2.2.0
    vite: "npm:@voidzero-dev/vite-plus-core@0.2.7"
    vite-plus: 0.3.0
  prod:
    react: 19.2.7
    react-dom: 19.2.7
    valibot: 1.4.2

minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.2.7"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.2.7"
  - "@voidzero-dev/vite-plus-darwin-x64@0.2.7"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.7"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.2.7"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.2.7"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.2.7"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.7"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.2.7"
  - vite-plus@0.2.7

overrides:
  vite: "npm:@voidzero-dev/vite-plus-core@0.3.0"

packages:
  - "internal/frontend"
  - "packages/**"
