name: publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-slim
    outputs:
      core-release-created: ${{ steps.release.outputs['packages/core--release_created'] }}
      core-tag-name: ${{ steps.release.outputs['packages/core--tag_name'] }}
      viewer-release-created: ${{ steps.release.outputs['packages/viewer--release_created'] }}
      viewer-tag-name: ${{ steps.release.outputs['packages/viewer--tag_name'] }}
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
          permission-issues: write

      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}

  npm:
    runs-on: ubuntu-24.04
    needs: release-please
    if: >-
      needs.release-please.outputs.core-release-created == 'true' ||
      needs.release-please.outputs.viewer-release-created == 'true'
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: ./.github/actions/setup

      - name: Use npm with trusted publishing support
        run: npm install --global npm@11.18.0

      - name: Publish @sushichan044/kg-core
        if: needs.release-please.outputs.core-release-created == 'true'
        run: pnpm --filter @sushichan044/kg-core publish --no-git-checks

      - name: Undraft @sushichan044/kg-core release
        if: needs.release-please.outputs.core-release-created == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release edit ${{ needs.release-please.outputs.core-tag-name }} --draft=false

      - name: Publish @sushichan044/kg-viewer
        if: needs.release-please.outputs.viewer-release-created == 'true'
        run: pnpm --filter @sushichan044/kg-viewer publish --no-git-checks

      - name: Undraft @sushichan044/kg-viewer release
        if: needs.release-please.outputs.viewer-release-created == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release edit ${{ needs.release-please.outputs.viewer-tag-name }} --draft=false
