name: release-please

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
          permission-issues: write

      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        if: >-
          steps.release.outputs['packages/core--release_created'] == 'true' ||
          steps.release.outputs['packages/viewer--release_created'] == 'true'

      - uses: ./.github/actions/setup
        if: >-
          steps.release.outputs['packages/core--release_created'] == 'true' ||
          steps.release.outputs['packages/viewer--release_created'] == 'true'
        with:
          go-version-file: go.mod

      - name: Use npm with trusted publishing support
        if: >-
          steps.release.outputs['packages/core--release_created'] == 'true' ||
          steps.release.outputs['packages/viewer--release_created'] == 'true'
        run: npm install --global npm@11.5.1

      - name: Publish @sushichan044/kg-core
        if: steps.release.outputs['packages/core--release_created'] == 'true'
        run: pnpm --filter @sushichan044/kg-core publish --no-git-checks

      - name: Publish @sushichan044/kg-viewer
        if: steps.release.outputs['packages/viewer--release_created'] == 'true'
        run: pnpm --filter @sushichan044/kg-viewer publish --no-git-checks
